style: reformat files
Signed-off-by: Ar Rakin <rakinar2@onesoftnet.eu.org>

diff --git a/dist/distupload b/dist/distupload
--- a/dist/distupload
+++ b/dist/distupload
@@ -3,12 +3,12 @@
 # distupload -- a script to upload software distributions to a server
 #
 # This script is part of OSN Commons. Copyright (C) 2024 OSN, Inc.
-# 
+#
 # OSN Commons is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
-# 
+#
 # OSN Commons is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@@ -28,7 +28,7 @@ fi
 version="1.0.0"
 
 check_requirements() {
-    if [ -z "$(command -v grep)" ]; then 
+    if [ -z "$(command -v grep)" ]; then
         echo "$me: GNU grep is required to use this script" >&2
         exit 1
     fi
@@ -96,7 +96,7 @@ validate_domain() {
 
     if echo "$1" | grep -E "^$pattern$" >/dev/null 2>&1; then
         return
-    fi 
+    fi
 
     echo "$me: invalid domain '$1'" >&2
     exit 1
@@ -111,7 +111,7 @@ check_command() {
 }
 
 check_files() {
-    local output="";
+    local output=""
 
     for file in "$@"; do
         output=$(stat "$file" 2>&1)
@@ -141,7 +141,7 @@ generate_gpg_signature() {
         fi
 
         echo "$me: generating GPG signature for $file"
-        gpg --detach-sign  --armor -o - -- "$file" > "$file.sig"
+        gpg --detach-sign --armor -o - -- "$file" >"$file.sig"
 
         if [ $? -ne 0 ]; then
             echo "$me: failed to generate signature for $file" >&2
@@ -168,69 +168,69 @@ while [ $# -gt 0 ]; do
 
     if [ $posargs -eq 0 ]; then
         case "$1" in
-            -h|-\?|--help)
-                show_help
-                exit
-                ;;
-            -v|--version)
-                show_version
-                exit
-                ;;
-            -m|--method)
-                check_optarg $@
-                method="$2"
-                shift 2
-                ;;
-            -q|--quiet)
-                quiet=1
-                shift
-                ;;
-            -r|--remote)
-                check_optarg $@
-                validate_domain "$2"
-                remote="$2"
-                shift 2
-                ;;
-            -l|--location)
-                check_optarg $@
-                location="$2"
-                shift 2
-                ;;
-            -p|--password)
-                check_optarg $@
-                password="$2"
-                shift 2
-                ;;
-            -u|--username)
-                if [ -z "$2" ]; then
-                    username="$USER"
-                else 
-                    username="$2"
-                fi
+        -h | -\? | --help)
+            show_help
+            exit
+            ;;
+        -v | --version)
+            show_version
+            exit
+            ;;
+        -m | --method)
+            check_optarg $@
+            method="$2"
+            shift 2
+            ;;
+        -q | --quiet)
+            quiet=1
+            shift
+            ;;
+        -r | --remote)
+            check_optarg $@
+            validate_domain "$2"
+            remote="$2"
+            shift 2
+            ;;
+        -l | --location)
+            check_optarg $@
+            location="$2"
+            shift 2
+            ;;
+        -p | --password)
+            check_optarg $@
+            password="$2"
+            shift 2
+            ;;
+        -u | --username)
+            if [ -z "$2" ]; then
+                username="$USER"
+            else
+                username="$2"
+            fi
 
-                shift 2
-                ;;
-            --)
-                posargs=1
-                shift
-                ;;
-            -*)
-                echo "$me: invalid option -- '$1'" >&2
-                echo "Try '$me --help' for more information" >&2
-                exit 1
-                ;;
-            *)
-                ended=1
+            shift 2
+            ;;
+        --)
+            posargs=1
+            shift
+            ;;
+        -*)
+            echo "$me: invalid option -- '$1'" >&2
+            echo "Try '$me --help' for more information" >&2
+            exit 1
+            ;;
+        *)
+            ended=1
             ;;
         esac
     else
         ended=1
     fi
 
-    if [ $ended -eq 1 ]; then 
+    if [ $ended -eq 1 ]; then
         if [ ! -z "$files" ]; then
             files="$files "
-        fi 
+        fi
 
         if echo "$file_name" | grep -q "[\ \'\"]"; then
             echo "$me: file names must not contain spaces or quotes" >&2
@@ -258,7 +258,7 @@ fi
 
 echo "$me: using $method to upload files to $target:$location"
 
-if [ ! -z "$username" ]; then 
+if [ ! -z "$username" ]; then
     echo "$me: authenticating as $username"
 fi
 
@@ -277,81 +277,81 @@ files="$files $sigs"
 time_start=$(date +%s)
 
 case $method in
-    scp)
-        check_command scp
+scp)
+    check_command scp
 
-        if [ ! -z "$password" ]; then 
-            echo "$me: cannot make any use of the password provided via command line options when using scp"
-            echo "$me: please enter the password when asked by scp"
-        fi 
-        
-        if [ $quiet -eq 1 ]; then
-            scp -- $files "$target:$location" > /dev/null 2>&1
-        else
-            scp -- $files "$target:$location"
-        fi
+    if [ ! -z "$password" ]; then
+        echo "$me: cannot make any use of the password provided via command line options when using scp"
+        echo "$me: please enter the password when asked by scp"
+    fi
 
-        code=$?
-        
-        if [ $code -ne 0 ]; then
-            echo "$me: scp failed with exit code $code" >&2
-            exit 1
-        fi
-    ;;
+    if [ $quiet -eq 1 ]; then
+        scp -- $files "$target:$location" >/dev/null 2>&1
+    else
+        scp -- $files "$target:$location"
+    fi
 
-    ftp|sftp)
-        check_command $method
+    code=$?
 
-        if [ -z "$username" ]; then 
-            echo "$me: no username provided, using 'anonymous' as default"
-            username=anonymous
-        fi 
-
-        batch_file=$(mktemp)
-
-        if [ $? -ne 0 ]; then
-            echo "$me: failed to create temporary file" >&2
-            exit 1
-        fi
-
-        if [ "$method" = "ftp" ]; then
-            echo "user \"$username\" \"$password\"" > "$batch_file"
-            echo "passive on" >> "$batch_file"
-        fi
-
-        echo "cd $location" >> "$batch_file"
-
-        for file in $files; do
-            echo "put $file" >> "$batch_file"
-        done
-        
-        echo "bye" >> "$batch_file"
-
-        if [ "$method" = "sftp" ]; then
-            if [ $quiet -eq 1 ]; then
-                sftp -oBatchMode=no -b "$batch_file" "$target" > /dev/null 2>&1
-            else
-                sftp -oBatchMode=no -b "$batch_file" "$target"
-            fi
-        else
-            if [ $quiet -eq 1 ]; then
-                cat "$batch_file" | $method -inv "$remote" > /dev/null 2>&1
-            else
-                cat "$batch_file" | $method -inv "$remote"
-            fi
-        fi
-
-        code=$?
-        
-        if [ $code -ne 0 ]; then
-            echo "$me: $method failed with exit code $code" >&2
-            exit 1
-        fi
-    ;;
-
-    *)
-        echo "$me: unsupported method '$method'" >&2
+    if [ $code -ne 0 ]; then
+        echo "$me: scp failed with exit code $code" >&2
         exit 1
+    fi
+    ;;
+
+ftp | sftp)
+    check_command $method
+
+    if [ -z "$username" ]; then
+        echo "$me: no username provided, using 'anonymous' as default"
+        username=anonymous
+    fi
+
+    batch_file=$(mktemp)
+
+    if [ $? -ne 0 ]; then
+        echo "$me: failed to create temporary file" >&2
+        exit 1
+    fi
+
+    if [ "$method" = "ftp" ]; then
+        echo "user \"$username\" \"$password\"" >"$batch_file"
+        echo "passive on" >>"$batch_file"
+    fi
+
+    echo "cd $location" >>"$batch_file"
+
+    for file in $files; do
+        echo "put $file" >>"$batch_file"
+    done
+
+    echo "bye" >>"$batch_file"
+
+    if [ "$method" = "sftp" ]; then
+        if [ $quiet -eq 1 ]; then
+            sftp -oBatchMode=no -b "$batch_file" "$target" >/dev/null 2>&1
+        else
+            sftp -oBatchMode=no -b "$batch_file" "$target"
+        fi
+    else
+        if [ $quiet -eq 1 ]; then
+            cat "$batch_file" | $method -inv "$remote" >/dev/null 2>&1
+        else
+            cat "$batch_file" | $method -inv "$remote"
+        fi
+    fi
+
+    code=$?
+
+    if [ $code -ne 0 ]; then
+        echo "$me: $method failed with exit code $code" >&2
+        exit 1
+    fi
+    ;;
+
+*)
+    echo "$me: unsupported method '$method'" >&2
+    exit 1
     ;;
 esac
 
diff --git a/dist/mkdist b/dist/mkdist
--- a/dist/mkdist
+++ b/dist/mkdist
@@ -3,12 +3,12 @@
 # mkdist -- a script to create software distributions
 #
 # This script is part of OSN Commons. Copyright (C) 2024 OSN, Inc.
-# 
+#
 # OSN Commons is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
-# 
+#
 # OSN Commons is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@@ -28,22 +28,22 @@ fi
 version="1.0.0"
 
 check_requirements() {
-    if [ -z "$(command -v tar)" ]; then 
+    if [ -z "$(command -v tar)" ]; then
         echo "$me: GNU tar is required to use this script" >&2
         exit 1
     fi
 
-    if [ -z "$(command -v jq)" ]; then 
+    if [ -z "$(command -v jq)" ]; then
         echo "$me: jq is required to use this script" >&2
         exit 1
     fi
 
-    if [ -z "$(command -v rsync)" ]; then 
+    if [ -z "$(command -v rsync)" ]; then
         echo "$me: rsync is required to use this script" >&2
         exit 1
     fi
 
-    if [ -z "$(command -v sed)" ]; then 
+    if [ -z "$(command -v sed)" ]; then
         echo "$me: sed is required to use this script" >&2
         exit 1
     fi
@@ -98,7 +98,7 @@ EOF
 }
 
 stat_directory() {
-    local result;
+    local result
     result=$(stat "$1" 2>&1)
 
     if [ $? -ne 0 ]; then
@@ -207,68 +207,68 @@ while [ $# -gt 0 ]; do
     fi
 
     case $1 in
-        -h|--help)
-            show_help
-            exit 0
-            ;;
-        -v|--version)
-            show_version
-            exit 0
-            ;;
-        -f|--formats)
-            check_optarg $@
-            shift
-            formats=$(echo $1 | tr ',' ' ')
-            ;;
-        -o|--output-path)
-            check_optarg $@
-            shift
-            output_path=$1
-            ;;
-        -n|--output-basename)
-            check_optarg $@
-            shift
-            output_basename="$1"
-            ;;
-        -e|--exclude)
-            check_optarg $@
-            shift
-            escaped=$(echo "$1" | sed 's/"/\\"/g')
-            excludes="$excludes --exclude \"$escaped\""
-            ;;
-        --exclude-from)
-            check_optarg $@
-            shift
-            escaped=$(echo "$1" | sed 's/"/\\"/g')
-            excludes="$excludes --exclude-from \"$escaped\""
-            ;;
-        -t|--archive-version)
-            check_optarg $@
-            shift
-            archive_version="$1"
-            ;;
-        -V|--verbose)
-            verbose=1
-            ;;
-        --)
-            posarg_start=1
-            shift
-            break
-            ;;
-        -*)
-            echo "$me: invalid option '$1'" >&2
+    -h | --help)
+        show_help
+        exit 0
+        ;;
+    -v | --version)
+        show_version
+        exit 0
+        ;;
+    -f | --formats)
+        check_optarg $@
+        shift
+        formats=$(echo $1 | tr ',' ' ')
+        ;;
+    -o | --output-path)
+        check_optarg $@
+        shift
+        output_path=$1
+        ;;
+    -n | --output-basename)
+        check_optarg $@
+        shift
+        output_basename="$1"
+        ;;
+    -e | --exclude)
+        check_optarg $@
+        shift
+        escaped=$(echo "$1" | sed 's/"/\\"/g')
+        excludes="$excludes --exclude \"$escaped\""
+        ;;
+    --exclude-from)
+        check_optarg $@
+        shift
+        escaped=$(echo "$1" | sed 's/"/\\"/g')
+        excludes="$excludes --exclude-from \"$escaped\""
+        ;;
+    -t | --archive-version)
+        check_optarg $@
+        shift
+        archive_version="$1"
+        ;;
+    -V | --verbose)
+        verbose=1
+        ;;
+    --)
+        posarg_start=1
+        shift
+        break
+        ;;
+    -*)
+        echo "$me: invalid option '$1'" >&2
+        echo "Try '$me --help' for more information." >&2
+        exit 1
+        ;;
+    *)
+        if [ ! -z "$target" ]; then
+            echo "$me: too many arguments provided" >&2
             echo "Try '$me --help' for more information." >&2
             exit 1
-            ;;
-        *)
-            if [ ! -z "$target" ]; then
-                echo "$me: too many arguments provided" >&2
-                echo "Try '$me --help' for more information." >&2
-                exit 1
-            fi
+        fi
 
-            target="$1"
-            ;;
+        target="$1"
+        ;;
     esac
     shift
 done
@@ -321,52 +321,52 @@ eval $rsync_cmd
 for format in "$formats"; do
     archive_name="${output_basename}-${archive_version}.$format"
 
-    if echo "$format" | grep -o "tar" > /dev/null 2>&1; then
-        echo "$archive_version" > $rsync_tmpdir/.tarball-version
+    if echo "$format" | grep -o "tar" >/dev/null 2>&1; then
+        echo "$archive_version" >$rsync_tmpdir/.tarball-version
     fi
 
     if [ "$format" = "zip" ]; then
-        echo "$archive_version" > $rsync_tmpdir/.zipball-version
+        echo "$archive_version" >$rsync_tmpdir/.zipball-version
     fi
 
     case "$format" in
-        tar.gz|tar.bz2|tar.xz)
-            flag=""
+    tar.gz | tar.bz2 | tar.xz)
+        flag=""
 
-            case "$format" in
-                tar.gz)
-                    flag="z"
-                    ;;
-                tar.bz2)
-                    flag="j"
-                    ;;
-                tar.xz)
-                    flag="J"
-                    ;;
-            esac
-
-            tar_cmd="tar -c${flag}f "$output_path/$archive_name" -C "$tmpdir" ."
-
-            if [ $verbose -eq 1 ]; then
-                echo "$me: executing: $tar_cmd"
-            fi
-
-            eval $tar_cmd
+        case "$format" in
+        tar.gz)
+            flag="z"
             ;;
-        zip)
-            zip_cmd="zip -r "$output_path/$archive_name" $tmpdir"
-
-            if [ $verbose -eq 1 ]; then
-                echo "$me: executing: $zip_cmd"
-            fi
-
-            eval $zip_cmd
+        tar.bz2)
+            flag="j"
             ;;
-        
-        *)
-            echo "$me: unsupported format '$format'" >&2
-            exit 1
+        tar.xz)
+            flag="J"
             ;;
+        esac
+
+        tar_cmd="tar -c${flag}f "$output_path/$archive_name" -C "$tmpdir" ."
+
+        if [ $verbose -eq 1 ]; then
+            echo "$me: executing: $tar_cmd"
+        fi
+
+        eval $tar_cmd
+        ;;
+    zip)
+        zip_cmd="zip -r "$output_path/$archive_name" $tmpdir"
+
+        if [ $verbose -eq 1 ]; then
+            echo "$me: executing: $zip_cmd"
+        fi
+
+        eval $zip_cmd
+        ;;
+
+    *)
+        echo "$me: unsupported format '$format'" >&2
+        exit 1
+        ;;
     esac
 
     rm -f $rsync_tmpdir/.tarball-version
@@ -375,7 +375,7 @@ done
 
 rm_flags=-rf
 
-if [ $verbose -eq 1 ]; then 
+if [ $verbose -eq 1 ]; then
     rm_flags="${rm_flags}v"
 fi
 
